### ISSUE TITLE
Bugs in update

### ISSUE THREAD

**Issue by Yabbertb** [thirtybees/productpaymentlogos#2]
A recent update introduced bugs into module. The postProcess() method does not save 'PRODUCTPAYMENTLOGOS_TITLE' and 'PRODUCTPAYMENTLOGOS_LINK' configurations. And I consider the lack of multilang for these fields a bug too.

**Comment by getdatakick** [comment]
Thanks, I missed this in code review.

Problem with saving is fixed in commit 0462db25cc7ae3cc65c8cd1280be31cbe29ceb5e, new module version is released.

Multilang support bughancement request is tracked in #3
